import './components/xy-button.js';
import './components/xy-slider.js';
import './components/xy-select.js';
import './components/xy-loading.js';
import './components/xy-tab.js';
import './components/xy-switch.js';
import './components/xy-checkbox.js';
import './components/xy-radio.js';
import './components/xy-tips.js';
import './components/xy-icon.js';
import './components/xy-layout.js';
import './components/xy-input.js';
import XyDialog from './components/xy-dialog.js';
import XyMessage from './components/xy-message.js';
window.XyDialog = XyDialog;
window.XyMessage = XyMessage;