import './components/xy-button.js';
import './components/xy-slider.js';
import './components/xy-select.js';
import './components/xy-loading.js';
import './components/xy-tab.js';
import './components/xy-switch.js';
import './components/xy-checkbox.js';
import './components/xy-radio.js';
import './components/xy-tips.js';
import './components/xy-icon.js';
import './components/xy-layout.js';
import './components/xy-input.js';
import './components/xy-img.js';
import './components/xy-rate.js';
import './components/xy-popover.js';
import './components/xy-color-picker.js';
import './components/xy-form.js';
import './components/xy-pagination.js';
import './components/xy-date-picker.js';
import './components/xy-table.js';
import './components/xy-text.js';
import './components/xy-view.js';
import './components/xy-datalist.js';
import XyDialog from './components/xy-dialog.js';
import XyMessage from './components/xy-message.js';
window.XyDialog = XyDialog;
window.XyMessage = XyMessage;