import './components/button/index.js';
import './components/slider/index.js';
import './components/switch/index.js';
import './components/tips/index.js';
import './components/checkbox/index.js';
import './components/icon/index.js';
import './components/loading/index.js';
import './components/radio/index.js';
// import './components/xy-select.js';
// import './components/xy-tab.js';
// import './components/xy-layout.js';
// import './components/xy-input.js';
// import './components/xy-img.js';
// import './components/xy-rate.js';
// import './components/xy-popover.js';
// import './components/xy-color-picker.js';
// import './components/xy-form.js';
// import './components/xy-pagination.js';
// import './components/xy-date-picker.js';
// import './components/xy-table.js';
// import './components/xy-text.js';
// import './components/xy-view.js';
// import './components/xy-datalist.js';
// import XyDialog from './components/xy-dialog.js';
// import XyMessage from './components/xy-message.js';
// window.XyDialog = XyDialog;
// window.XyMessage = XyMessage;